#!/usr/bin/env python3
"""Parallel, sharded, resumable Point-QA generation for large scale (e.g. 1M).

Why a separate driver:
  PointQAGenerator.generate() holds every scene point cloud in memory before
  writing, so a single 1M call would need tens of TB of RAM. This driver splits
  the target into many small shards, each generated by a worker process into its
  own subdir, bounding peak memory to (shard_size x avg_scene_bytes) per worker.

Each shard:
  - gets a distinct seed (base_seed + shard_index) so workers never produce
    identical scenes/QA;
  - writes to shards/shard_XXXXXX/ (tasks.jsonl + pcd/*.npy);
  - is skipped on resume if its _DONE marker exists.

After all shards finish, an index.jsonl is written at the output root with every
task and a `point` path relative to the root (shard_XXXXXX/pcd/NNNNNN.npy), so
training can glob the root without moving any TB-scale files.

Usage:
    python run_point_qa_gen_parallel.py --num-tasks 1000000 --output /path/out \
        --workers 64 --shard-size 200 --num-points 16384

    # resume (just rerun the same command; done shards are skipped)
"""
import os

# Pin numerical libraries to a SINGLE thread per process BEFORE importing numpy.
# We parallelize across processes (one shard per worker); letting numpy/BLAS also
# spin up one thread per core inside each of N workers causes N*cores threads to
# fight over the CPU (thread oversubscription), which made 64 workers crawl.
# Must be set before numpy is imported anywhere, hence at the very top.
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
           "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
    os.environ.setdefault(_v, "1")

import argparse
import hashlib
import json
import time
from multiprocessing import Pool

from point_qa_generator import PointQAGenerator, TaskPlan


DEFAULT_METADATA = os.environ.get(
    "ANYPOINT_METADATA",
    "/mnt/tidalfs-bdsz01/dataset/llm_ckpt/task/3d_data/anypoint_metadata_to_date.jsonl",
)
DEFAULT_PCD_DIR = os.environ.get(
    "ANYPOINT_PCD_DIR",
    "/mnt/tidalfs-bdsz01/dataset/llm_ckpt/task/3d_data/anypoint_meta_obj_npys",
)
DEFAULT_LAYOUTS = os.environ.get(
    "ANYPOINT_LAYOUTS",
    "/mnt/tidalfs-bdsz01/dataset/llm_ckpt/task/3d_data/layout_10k/layouts.jsonl",
)
DEFAULT_BACKGROUND = os.environ.get(
    "ANYPOINT_BACKGROUND",
    "/mnt/tidalfs-bdsz01/dataset/llm_ckpt/task/3d_data/background",
)

# Per-process generator, built once per worker (loading metadata is expensive).
_GEN = None
_CFG = None


def _init_worker(cfg):
    global _GEN, _CFG
    _CFG = cfg
    _GEN = PointQAGenerator(
        metadata_file=cfg["metadata"],
        pcd_dir=cfg["pcd_dir"],
        layouts_file=cfg["layouts"],
        seed=cfg["base_seed"],
        background_dir=cfg["background_dir"],
        cache_mb=cfg["cache_mb"],
    )


def _run_shard(job):
    """Generate one single-generator shard.

    job = (gen_type, shard_idx, n_tasks). Output goes to
    <output>/<gen_type>/shard_<idx>/ so the dataset is organized by generator.
    Returns (gen_type, shard_idx, n_tasks, seconds, skipped).
    """
    gen_type, shard_idx, n_tasks = job
    cfg = _CFG
    shard_dir = os.path.join(cfg["output"], gen_type, f"shard_{shard_idx:08d}")
    done_marker = os.path.join(shard_dir, "_DONE")
    if os.path.exists(done_marker):
        return gen_type, shard_idx, n_tasks, 0.0, True

    t0 = time.time()
    # Unique seed per (gen_type, shard) so shards never collide. Must stay in
    # numpy's legal RandomState range [0, 2**32 - 1].
    gen_hash = int(hashlib.sha256(gen_type.encode()).hexdigest(), 16) & 0xFFFFF
    seed = (cfg["base_seed"] + gen_hash * 4096 + shard_idx) % (2 ** 32 - 1)
    plan = TaskPlan(
        generator_type=gen_type,
        num_options=cfg["num_options"],
        seed=seed,
        generator_config=cfg["generator_config"],
    )
    _GEN.generate(plan, n_tasks, shard_dir, num_points=cfg["num_points"])
    with open(done_marker, "w") as f:
        f.write(json.dumps({"gen_type": gen_type, "n_tasks": n_tasks, "seed": seed}))
    return gen_type, shard_idx, n_tasks, time.time() - t0, False


def _plan_shards(num_tasks, shard_size, gen_types):
    """Distribute num_tasks evenly across generators, then chunk into shards.

    Returns list of (gen_type, shard_idx, n_tasks). Generator balance is exact
    (remainder spread over the first few generators).
    """
    n = len(gen_types)
    base, rem = divmod(num_tasks, n)
    # Build each generator's shard list separately...
    per_gen = []
    for gi, gt in enumerate(gen_types):
        quota = base + (1 if gi < rem else 0)
        shards, idx, remaining = [], 0, quota
        while remaining > 0:
            take = min(shard_size, remaining)
            shards.append((gt, idx, take))
            remaining -= take
            idx += 1
        per_gen.append(shards)
    # ...then interleave (round-robin) so all generators run concurrently from
    # the start. Without this, jobs run generator-by-generator: the slow
    # size/frequent generators would all queue at the very end and tail badly,
    # and an interrupted run would only cover the first few generators.
    jobs = []
    for i in range(max(len(s) for s in per_gen)):
        for shards in per_gen:
            if i < len(shards):
                jobs.append(shards[i])
    return jobs


def _build_index(output, gen_types):
    """Merge every <gen>/shard_*/tasks.jsonl into one root index.jsonl.

    Assigns a fresh global question_id (0..M) and rewrites `point` to a path
    relative to `output`: <gen>/shard_xxxxxxxx/pcd/xxxxxxxx.npy.
    No physical files are moved or renamed.
    """
    index_path = os.path.join(output, "index.jsonl")
    gid = 0
    per_gen = {}
    with open(index_path, "w", encoding="utf-8") as out:
        for gt in sorted(gen_types):
            gen_dir = os.path.join(output, gt)
            if not os.path.isdir(gen_dir):
                continue
            count = 0
            for shard_name in sorted(os.listdir(gen_dir)):
                sdir = os.path.join(gen_dir, shard_name)
                tjson = os.path.join(sdir, "tasks.jsonl")
                if not os.path.isdir(sdir) or not os.path.exists(tjson):
                    continue
                with open(tjson, encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        rec = json.loads(line)
                        rec["point"] = os.path.join(gt, shard_name, "pcd", rec["point"])
                        rec["generator"] = gt
                        rec["question_id"] = gid
                        gid += 1
                        count += 1
                        out.write(json.dumps(rec, ensure_ascii=False) + "\n")
            per_gen[gt] = count
    return index_path, gid, per_gen


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--num-tasks", type=int, required=True)
    ap.add_argument("--output", type=str, required=True)
    ap.add_argument("--workers", type=int, default=120)
    ap.add_argument("--shard-size", type=int, default=40,
                    help="tasks per shard; smaller = finer load-balancing across "
                         "workers (helps the slow size/frequent generators not tail), "
                         "but more shard dirs. Bounds per-worker memory.")
    ap.add_argument("--cache-mb", type=int, default=4096,
                    help="per-worker LRU cache budget (MB) for object point clouds; "
                         "the same ~20k objects recur across millions of scenes, so "
                         "caching hot ones avoids re-reading from the filesystem. "
                         "Total RAM = workers * cache-mb, keep it well under machine "
                         "memory. 0 disables.")
    ap.add_argument("--num-points", type=int, default=24576,
                    help="downsample each scene to N points before saving "
                         "(0 = full; default 24576 = 8192*3; scenes with fewer "
                         "points are kept as-is)")
    ap.add_argument("--types", nargs="*", help="generator types (default: all)")
    ap.add_argument("--num-options", type=str, default="4-6")
    ap.add_argument("--base-seed", type=int, default=42)
    ap.add_argument("--metadata", default=DEFAULT_METADATA)
    ap.add_argument("--pcd-dir", default=DEFAULT_PCD_DIR)
    ap.add_argument("--layouts", default=DEFAULT_LAYOUTS)
    ap.add_argument("--background-dir", default=DEFAULT_BACKGROUND)
    ap.add_argument("--no-index", action="store_true", help="skip building root index.jsonl")
    args = ap.parse_args()

    if "-" in args.num_options:
        lo, hi = args.num_options.split("-")
        num_options = (int(lo), int(hi))
    else:
        num_options = int(args.num_options)

    # Resolve generator types up-front (need the full list to balance across them).
    if args.types:
        gen_types = args.types
    else:
        probe = PointQAGenerator(
            metadata_file=args.metadata, pcd_dir=args.pcd_dir,
            layouts_file=args.layouts, seed=args.base_seed,
            background_dir=args.background_dir)
        gen_types = list(probe.generators.keys())
        del probe

    cfg = {
        "output": args.output,
        "metadata": args.metadata,
        "pcd_dir": args.pcd_dir,
        "layouts": args.layouts,
        "background_dir": args.background_dir,
        "base_seed": args.base_seed,
        "num_options": num_options,
        "generator_config": {},
        "num_points": args.num_points if args.num_points > 0 else None,
        "cache_mb": args.cache_mb,
    }

    os.makedirs(args.output, exist_ok=True)
    jobs = _plan_shards(args.num_tasks, args.shard_size, gen_types)

    print(f"Parallel Point-QA generation")
    print(f"  Target tasks : {args.num_tasks:,}")
    print(f"  Generators   : {len(gen_types)} (balanced ~{args.num_tasks // len(gen_types):,} each)")
    print(f"  Shards       : {len(jobs)} (<= {args.shard_size} tasks each)")
    print(f"  Workers      : {args.workers}")
    print(f"  Num points   : {cfg['num_points'] or 'full'}")
    print(f"  Output       : {args.output}")
    print()

    t0 = time.time()
    done = 0
    skipped = 0
    with Pool(processes=args.workers, initializer=_init_worker, initargs=(cfg,)) as pool:
        for gen_type, shard_idx, n, secs, was_skipped in pool.imap_unordered(_run_shard, jobs):
            done += 1
            if was_skipped:
                skipped += 1
            elapsed = time.time() - t0
            rate = (done - skipped) / elapsed if elapsed > 0 else 0
            eta = (len(jobs) - done) / rate if rate > 0 else 0
            print(f"  {gen_type}/shard_{shard_idx:08d} done ({n} tasks, {secs:.1f}s) | "
                  f"{done}/{len(jobs)} shards | ~{rate*args.shard_size:.0f} tasks/s | "
                  f"ETA {eta/60:.1f} min{' [resumed-skip]' if was_skipped else ''}")

    print(f"\nAll shards complete in {(time.time()-t0)/60:.1f} min "
          f"({skipped} skipped on resume)")

    if not args.no_index:
        print("Building root index.jsonl ...")
        index_path, total, per_gen = _build_index(args.output, gen_types)
        print(f"  Wrote {total:,} task records -> {index_path}")
        print("  Per-generator counts:")
        for gt in sorted(per_gen):
            print(f"    {gt:<28} {per_gen[gt]:,}")


if __name__ == "__main__":
    main()
