"""Question template library for diverse paraphrasing."""

from typing import Dict, List, Union
import numpy as np

TemplateTree = Union[List[str], Dict[str, "TemplateTree"]]

QUESTION_TEMPLATES: Dict[str, TemplateTree] = {
    "what_distance": {
        "closest": [
            "What is the object that is closest to the {ref}?",
            "Which object is nearest to the {ref}?",
            "Identify the object positioned closest to the {ref}.",
            "Among all objects, which one is the closest to the {ref}?",
            "What object has the shortest distance to the {ref}?",
            "Which item sits nearest to the {ref}?",
            "Name the object located closest to the {ref}.",
            "Of all the objects, which lies nearest the {ref}?",
            "Which object is the least distant from the {ref}?",
            "Point out the object that is nearest to the {ref}.",
            "What is the nearest object to the {ref}?",
            "Tell me which object is closest to the {ref}.",
        ],
        "farthest": [
            "What is the object that is farthest from the {ref}?",
            "Which object is the most distant from the {ref}?",
            "Identify the object positioned farthest from the {ref}.",
            "Among all objects, which one is the farthest from the {ref}?",
            "What object has the greatest distance from the {ref}?",
            "Which item sits farthest away from the {ref}?",
            "Name the object located farthest from the {ref}.",
            "Of all the objects, which lies farthest from the {ref}?",
            "Which object is the least close to the {ref}?",
            "Point out the object that is most remote from the {ref}.",
            "What is the most far-off object from the {ref}?",
            "Tell me which object is farthest from the {ref}.",
        ],
    },
    "where_distance": {
        "closest": [
            "Where is the object that is closest to the {ref}?",
            "In what direction is the nearest object relative to the {ref}?",
            "Describe the position of the closest object to the {ref}.",
            "What is the spatial relation of the nearest object to the {ref}?",
            "Relative to the {ref}, where is the closest object located?",
            "Which direction holds the nearest object to the {ref}?",
            "Where can the object closest to the {ref} be found?",
            "How is the nearest object positioned with respect to the {ref}?",
            "Locate the closest object relative to the {ref}.",
            "In relation to the {ref}, where does the nearest object sit?",
            "Where does the object closest to the {ref} lie?",
            "Give the position of the nearest object to the {ref}.",
        ],
        "farthest": [
            "Where is the object that is farthest from the {ref}?",
            "In what direction is the most distant object relative to the {ref}?",
            "Describe the position of the farthest object from the {ref}.",
            "What is the spatial relation of the farthest object to the {ref}?",
            "Relative to the {ref}, where is the farthest object located?",
            "Which direction holds the most distant object from the {ref}?",
            "Where can the object farthest from the {ref} be found?",
            "How is the farthest object positioned with respect to the {ref}?",
            "Locate the farthest object relative to the {ref}.",
            "In relation to the {ref}, where does the most distant object sit?",
            "Where does the object farthest from the {ref} lie?",
            "Give the position of the farthest object from the {ref}.",
        ],
    },
    "list_attribute_distance": {
        "closest": [
            "List all {attr}s in the components of the object closest to the {ref}.",
            "What are the {attr}s of the nearest object to the {ref}?",
            "Enumerate the {attr}s found in the object that is closest to the {ref}.",
            "Name every {attr} of the object nearest to the {ref}.",
            "Which {attr}s appear in the closest object to the {ref}?",
            "Report all the {attr}s of the object nearest the {ref}.",
            "What {attr}s does the object closest to the {ref} contain?",
            "Give the full list of {attr}s for the nearest object to the {ref}.",
            "Identify each {attr} present in the closest object to the {ref}.",
            "List the {attr}s belonging to the object nearest the {ref}.",
        ],
        "farthest": [
            "List all {attr}s in the components of the object farthest from the {ref}.",
            "What are the {attr}s of the most distant object from the {ref}?",
            "Enumerate the {attr}s found in the object that is farthest from the {ref}.",
            "Name every {attr} of the object farthest from the {ref}.",
            "Which {attr}s appear in the farthest object from the {ref}?",
            "Report all the {attr}s of the object most distant from the {ref}.",
            "What {attr}s does the object farthest from the {ref} contain?",
            "Give the full list of {attr}s for the most distant object from the {ref}.",
            "Identify each {attr} present in the farthest object from the {ref}.",
            "List the {attr}s belonging to the object farthest from the {ref}.",
        ],
    },
    "count_attribute_distance": {
        "closest": [
            "How many {attr}s are in the components of the object closest to the {ref}?",
            "Count the distinct {attr}s of the nearest object to the {ref}.",
            "How many unique {attr}s does the closest object to the {ref} have?",
            "What is the number of different {attr}s in the object nearest the {ref}?",
            "Tally the distinct {attr}s of the closest object to the {ref}.",
            "How many separate {attr}s does the nearest object to the {ref} possess?",
            "Give the count of unique {attr}s in the object closest to the {ref}.",
            "How many kinds of {attr} appear in the nearest object to the {ref}?",
            "Determine the number of distinct {attr}s in the closest object to the {ref}.",
            "What count of {attr}s does the object nearest the {ref} have?",
        ],
        "farthest": [
            "How many {attr}s are in the components of the object farthest from the {ref}?",
            "Count the distinct {attr}s of the most distant object from the {ref}.",
            "How many unique {attr}s does the farthest object from the {ref} have?",
            "What is the number of different {attr}s in the object farthest from the {ref}?",
            "Tally the distinct {attr}s of the farthest object from the {ref}.",
            "How many separate {attr}s does the most distant object from the {ref} possess?",
            "Give the count of unique {attr}s in the object farthest from the {ref}.",
            "How many kinds of {attr} appear in the farthest object from the {ref}?",
            "Determine the number of distinct {attr}s in the farthest object from the {ref}.",
            "What count of {attr}s does the object farthest from the {ref} have?",
        ],
    },
    "what_attribute": [
        "What is the {attr} of the {comp} in the {obj}?",
        "Identify the {attr} of the {comp} component of the {obj}.",
        "What {attr} does the {comp} of the {obj} have?",
        "Describe the {attr} property of the {comp} in the {obj}.",
        "What is the {comp}'s {attr} in the {obj}?",
        "State the {attr} of the {comp} belonging to the {obj}.",
        "Which {attr} is associated with the {comp} of the {obj}?",
        "Tell me the {attr} of the {comp} in the {obj}.",
        "For the {obj}, what {attr} does its {comp} have?",
        "What {attr} characterizes the {comp} of the {obj}?",
        "Report the {attr} of the {comp} part of the {obj}.",
        "Give the {attr} of the {comp} in the {obj}.",
    ],
    "list_attribute": [
        "List all {attr}s in the components of the {obj}.",
        "What are all the {attr}s found in the {obj}'s components?",
        "Enumerate the {attr}s present in the components of the {obj}.",
        "Name all distinct {attr}s in the {obj}.",
        "Which {attr}s appear across the components of the {obj}?",
        "Provide every {attr} found in the {obj}.",
        "Report all the {attr}s belonging to the {obj}'s components.",
        "What {attr}s does the {obj} have across its parts?",
        "Give the complete list of {attr}s in the {obj}.",
        "Identify each {attr} present in the components of the {obj}.",
        "List out the {attr}s contained in the {obj}.",
        "Spell out all {attr}s found in the {obj}'s components.",
    ],
    "count_attribute": [
        "How many distinct {attr}s are in the components of the {obj}?",
        "Count the number of different {attr}s in the {obj}'s components.",
        "How many unique {attr}s does the {obj} have across its components?",
        "What is the number of distinct {attr}s in the {obj}?",
        "Tally the different {attr}s found in the {obj}'s components.",
        "How many separate {attr}s does the {obj} contain?",
        "Give the count of unique {attr}s across the {obj}'s parts.",
        "How many kinds of {attr} appear in the {obj}?",
        "Determine the number of distinct {attr}s in the {obj}.",
        "What count of different {attr}s does the {obj} have?",
    ],
    "count_object": [
        "How many {obj} are in the scene?",
        "Count the number of {obj} in the scene.",
        "How many instances of {obj} can you find in this scene?",
        "What is the total count of {obj} in the scene?",
        "How many {obj} appear in this scene?",
        "Tally the {obj} present in the scene.",
        "What number of {obj} are there in the scene?",
        "How many times does {obj} occur in the scene?",
        "Determine how many {obj} are in the scene.",
        "Give the total number of {obj} shown in the scene.",
        "How many copies of {obj} are visible in the scene?",
        "Count how many {obj} exist in this scene.",
    ],
    "frequent_object": {
        "most": [
            "What is the most frequent object in the scene?",
            "Which object appears the most times in the scene?",
            "Identify the object with the highest count in this scene.",
            "What object has the most instances in the scene?",
            "Which object occurs most often in the scene?",
            "Name the object that shows up most frequently in the scene.",
            "What is the most commonly repeated object in the scene?",
            "Which object is repeated the greatest number of times here?",
            "Point out the object appearing most often in this scene.",
            "What object recurs the most in the scene?",
            "Which is the most numerous object in the scene?",
            "Tell me which object appears most frequently in the scene.",
        ],
        "least": [
            "What is the least frequent object in the scene?",
            "Which object appears the fewest times in the scene?",
            "Identify the object with the lowest count in this scene.",
            "What object has the fewest instances in the scene?",
            "Which object occurs least often in the scene?",
            "Name the object that shows up least frequently in the scene.",
            "What is the most rarely repeated object in the scene?",
            "Which object is repeated the fewest number of times here?",
            "Point out the object appearing least often in this scene.",
            "What object recurs the least in the scene?",
            "Which is the least numerous object in the scene?",
            "Tell me which object appears least frequently in the scene.",
        ],
    },
    "list_attribute_frequent": {
        "most": [
            "List all {attr}s in the components of the most frequent object in the scene.",
            "What {attr}s does the most common object in the scene have?",
            "Enumerate the {attr}s of the object that appears most often.",
            "Name every {attr} of the most frequent object in the scene.",
            "Which {attr}s belong to the object that occurs most often?",
            "Report all the {attr}s of the most repeated object in the scene.",
            "What {attr}s are found in the most numerous object in the scene?",
            "Give the full list of {attr}s for the most frequent object.",
            "Identify each {attr} of the object appearing most often in the scene.",
            "List the {attr}s of the scene's most common object.",
        ],
        "least": [
            "List all {attr}s in the components of the least frequent object in the scene.",
            "What {attr}s does the rarest object in the scene have?",
            "Enumerate the {attr}s of the object that appears least often.",
            "Name every {attr} of the least frequent object in the scene.",
            "Which {attr}s belong to the object that occurs least often?",
            "Report all the {attr}s of the least repeated object in the scene.",
            "What {attr}s are found in the least numerous object in the scene?",
            "Give the full list of {attr}s for the least frequent object.",
            "Identify each {attr} of the object appearing least often in the scene.",
            "List the {attr}s of the scene's rarest object.",
        ],
    },
    "count_attribute_frequent": {
        "most": [
            "How many {attr}s are in the components of the most frequent object?",
            "Count the distinct {attr}s of the most common object in the scene.",
            "How many unique {attr}s does the most frequent object have?",
            "What is the number of different {attr}s in the most repeated object?",
            "Tally the distinct {attr}s of the scene's most common object.",
            "How many separate {attr}s does the most numerous object possess?",
            "Give the count of unique {attr}s in the most frequent object.",
            "How many kinds of {attr} appear in the most common object?",
            "Determine the number of distinct {attr}s in the most frequent object.",
            "What count of {attr}s does the most often repeated object have?",
        ],
        "least": [
            "How many {attr}s are in the components of the least frequent object?",
            "Count the distinct {attr}s of the rarest object in the scene.",
            "How many unique {attr}s does the least frequent object have?",
            "What is the number of different {attr}s in the least repeated object?",
            "Tally the distinct {attr}s of the scene's rarest object.",
            "How many separate {attr}s does the least numerous object possess?",
            "Give the count of unique {attr}s in the least frequent object.",
            "How many kinds of {attr} appear in the rarest object?",
            "Determine the number of distinct {attr}s in the least frequent object.",
            "What count of {attr}s does the least often repeated object have?",
        ],
    },
    "what_size": {
        "largest": [
            "What is the largest object in the scene?",
            "Which object has the greatest volume in the scene?",
            "Identify the biggest object in this scene.",
            "What is the most voluminous object here?",
            "Which is the biggest object present in the scene?",
            "Name the object that takes up the most space in the scene.",
            "What object occupies the greatest volume here?",
            "Which object is the largest in size in this scene?",
            "Point out the biggest object in the scene.",
            "Of all the objects, which is the largest?",
            "What is the most sizable object in the scene?",
            "Tell me which object is the largest here.",
        ],
        "smallest": [
            "What is the smallest object in the scene?",
            "Which object has the least volume in the scene?",
            "Identify the tiniest object in this scene.",
            "What is the most compact object here?",
            "Which is the smallest object present in the scene?",
            "Name the object that takes up the least space in the scene.",
            "What object occupies the smallest volume here?",
            "Which object is the smallest in size in this scene?",
            "Point out the tiniest object in the scene.",
            "Of all the objects, which is the smallest?",
            "What is the least sizable object in the scene?",
            "Tell me which object is the smallest here.",
        ],
    },
    "list_attribute_size": {
        "largest": [
            "List all {attr}s in the components of the largest object in the scene.",
            "What {attr}s does the biggest object in this scene have?",
            "Enumerate the {attr}s of the largest object.",
            "Name every {attr} of the biggest object in the scene.",
            "Which {attr}s belong to the largest object in the scene?",
            "Report all the {attr}s of the most voluminous object.",
            "What {attr}s are found in the scene's biggest object?",
            "Give the full list of {attr}s for the largest object.",
            "Identify each {attr} of the biggest object in the scene.",
            "List the {attr}s contained in the largest object.",
        ],
        "smallest": [
            "List all {attr}s in the components of the smallest object in the scene.",
            "What {attr}s does the tiniest object in this scene have?",
            "Enumerate the {attr}s of the smallest object.",
            "Name every {attr} of the tiniest object in the scene.",
            "Which {attr}s belong to the smallest object in the scene?",
            "Report all the {attr}s of the most compact object.",
            "What {attr}s are found in the scene's smallest object?",
            "Give the full list of {attr}s for the smallest object.",
            "Identify each {attr} of the tiniest object in the scene.",
            "List the {attr}s contained in the smallest object.",
        ],
    },
    "count_attribute_size": {
        "largest": [
            "How many {attr}s are in the components of the largest object?",
            "Count the distinct {attr}s of the biggest object in the scene.",
            "How many unique {attr}s does the largest object have?",
            "What is the number of different {attr}s in the biggest object?",
            "Tally the distinct {attr}s of the scene's largest object.",
            "How many separate {attr}s does the most voluminous object possess?",
            "Give the count of unique {attr}s in the largest object.",
            "How many kinds of {attr} appear in the biggest object?",
            "Determine the number of distinct {attr}s in the largest object.",
            "What count of {attr}s does the biggest object have?",
        ],
        "smallest": [
            "How many {attr}s are in the components of the smallest object?",
            "Count the distinct {attr}s of the tiniest object in the scene.",
            "How many unique {attr}s does the smallest object have?",
            "What is the number of different {attr}s in the tiniest object?",
            "Tally the distinct {attr}s of the scene's smallest object.",
            "How many separate {attr}s does the most compact object possess?",
            "Give the count of unique {attr}s in the smallest object.",
            "How many kinds of {attr} appear in the tiniest object?",
            "Determine the number of distinct {attr}s in the smallest object.",
            "What count of {attr}s does the tiniest object have?",
        ],
    },
    "where_size": {
        "with_reference": {
            "largest": [
                "Where is the largest object relative to the {ref}?",
                "What is the spatial position of the biggest object with respect to the {ref}?",
                "Describe where the largest object is in relation to the {ref}.",
                "Relative to the {ref}, where does the biggest object sit?",
                "In what direction is the largest object from the {ref}?",
                "How is the biggest object positioned with respect to the {ref}?",
                "Locate the largest object in relation to the {ref}.",
                "Where can the biggest object be found relative to the {ref}?",
            ],
            "smallest": [
                "Where is the smallest object relative to the {ref}?",
                "What is the spatial position of the tiniest object with respect to the {ref}?",
                "Describe where the smallest object is in relation to the {ref}.",
                "Relative to the {ref}, where does the tiniest object sit?",
                "In what direction is the smallest object from the {ref}?",
                "How is the tiniest object positioned with respect to the {ref}?",
                "Locate the smallest object in relation to the {ref}.",
                "Where can the tiniest object be found relative to the {ref}?",
            ],
        },
        "reference_to_target": {
            "largest": [
                "Where is the {ref} relative to the largest object?",
                "Describe the position of the {ref} with respect to the biggest object.",
                "In what direction is the {ref} from the largest object?",
                "How is the {ref} positioned relative to the biggest object?",
                "Locate the {ref} in relation to the largest object.",
                "Relative to the biggest object, where does the {ref} sit?",
            ],
            "smallest": [
                "Where is the {ref} relative to the smallest object?",
                "Describe the position of the {ref} with respect to the tiniest object.",
                "In what direction is the {ref} from the smallest object?",
                "How is the {ref} positioned relative to the tiniest object?",
                "Locate the {ref} in relation to the smallest object.",
                "Relative to the tiniest object, where does the {ref} sit?",
            ],
        },
    },
    "what_relation": [
        "What is the object that is {rel} the {ref}?",
        "Which object is {rel} the {ref}?",
        "Identify the object {rel} the {ref}.",
        "What object is positioned {rel} the {ref}?",
        "Which item is located {rel} the {ref}?",
        "Name the object that sits {rel} the {ref}.",
        "What object can be found {rel} the {ref}?",
        "Point out the object {rel} the {ref}.",
        "Tell me which object is {rel} the {ref}.",
        "Which object lies {rel} the {ref}?",
        "What is positioned {rel} the {ref}?",
        "Identify which object is {rel} the {ref}.",
    ],
    "multi_hop_relation": [
        "What is the object {rel2} the object {rel1} the {anchor}?",
        "Which object is {rel2} the object that is {rel1} the {anchor}?",
        "Identify the object that is {rel2} the one {rel1} the {anchor}.",
        "Find the object {rel2} the object {rel1} the {anchor}.",
        "What object sits {rel2} the object that is {rel1} the {anchor}?",
        "Name the object {rel2} the one that is {rel1} the {anchor}.",
        "Which item is {rel2} the object located {rel1} the {anchor}?",
        "Point out the object {rel2} the object {rel1} the {anchor}.",
        "Tell me what object is {rel2} the object {rel1} the {anchor}.",
        "What is located {rel2} the object that is {rel1} the {anchor}?",
    ],
}


def sample_template(rng: np.random.RandomState, generator_type: str, **kwargs) -> str:
    """Sample a random question template for the given generator type and config."""
    templates = QUESTION_TEMPLATES[generator_type]

    # Traverse nested dict using known config keys
    lookup_keys = ["distance_type", "frequency_type", "reference_mode", "size_type"]
    for key in lookup_keys:
        if isinstance(templates, dict) and key in kwargs:
            sub_key = kwargs[key]
            if sub_key in templates:
                templates = templates[sub_key]

    if isinstance(templates, list):
        return templates[rng.randint(len(templates))]

    # Fallback: pick first available list
    while isinstance(templates, dict):
        templates = next(iter(templates.values()))
    if isinstance(templates, list):
        return templates[rng.randint(len(templates))]

    return templates
